= Sprint #19 Product Backlog Refinement

== Attachment (Read)

* NOTE: Document ACL is not supported
** Write a failing acceptance test here
** Update spec with some warnings
* NOTE: Document nested messages are not supported
** Write a failing acceptance test here
** Update spec with some warnings
* TASK: Support inline attachment
* TASK: Support messages with mixed (html and text) content (special multipart case?)
* TASK: Support attachments naming in getMessages and download end point

== Attachment (Write)

* TASK: upload API
** NOTE: does not handle quota
* TASK: update SetMessage to support attachment with blobId
** construct a multipart message with mime4j (lib is already used)
* TASK: use a simple Cassandra TTL to handle upload expiration
** remove TTL once file is referenced
** use Attachment table to store data
** load the whole file in memory for a start
* TASK: handle a max size for upload
* TASK: support inline attachment
* TASK: generate mixed content (text + html)?
* TASK: support attachments naming in setMessages

== Search

* TASK: port ES test suite to Scanning Search and Lucene
* TASK: demonstrate with a test that mailbox renaming works
* TASK: deserialize Filter tree into a POJO tree
* TASK: map the Filter POJO tree to a SearchQuery
** NOTE: no Thread* support
* TASK: make hasAttachment searchable via mailbox-api
* TASK: make GetMessagesList call the search api
* TASK: multi-mailbox support in GetMessagesList
** NOTE: index users that have access to a message
** NOTE: add an api in MessageSearchIndex to query regarless of a mailbox
** NOTE: add inMailboxes and notInMailboxes into SearchQuery
** NOTE: implement trivial inMailboxes and notInMailboxes filtering into all MessageSearchIndex implementations

== Questions

* Do we want to manage quota on upload ? Ask that with INBOX and UX team
** Answer : We don't care right now
* How hard would it be to filter on mailbox and/or users when use Filter on GetMessagesList
** Answer: very. Off course no user indexing at all. James filtering API needs a Mailbox to search on. So it is not possible to compose any filter containing requests such as (inMailboxes=... or notInMailboxes=...). If we don't need compositing or a very simple compositing (2 clauses) the problem can be solved in JMAP backend. To have a plain support we need to end or work on unifying UID, ie a message should have a single id whatever is its mailbox. The good news: elasticsearch is already basing its indexing on such an UID, so maybe extending the API could fit our need for now.
* How hard is it the handle mailbox rename for search ?
** Answer : It should work right now because mailboxId doesn't change on rename. We have to write a test anyway.

* Do we have an implementation that works without requiring filesystem and that is fast to start for InMemory tests ?
** Lucene search is not really tested but should support InMemory
** There's a scanning search implementation, it's slow but should work
** IMAP only ask for substring matching, but JMAP suggest full text search
** ES does not conform to IMAP search but is ok for JMAP
** JMAP says `The exact semantics for matching String fields is deliberately not defined to allow for flexibility in indexing implementation, subject to the following` so any impl should be ok, we only have to be careful about test involving tests
** ES helps implementing https://tools.ietf.org/html/rfc6237 
** We can make UidSearchOnIndex and ElasticSearchIntegrationTest to run on all search impl
