= Sprint #20 Product Backlog Refinement

== Search

* TASK: port ES test suite to Scanning Search and Lucene
** NOTE: report test coverage, don't implement features

3 pts

* TASK: deserialize Filter tree into a POJO tree (JSON in, POJO out)
** NOTE: generate a toString for the tree

3 pts

* TASK: make hasAttachment searchable via mailbox-api
** NOTE: update ES schema
** NOTE: add the criterion to SearchQuery
** NOTE: implement hasAttachment filtering into 3 backends
** NOTE: must be done before Filter to SearchQuery conversion

3 pts

* TASK: index users that have access to a message
** NOTE: update ES schema
** NOTE: add user filter when executing any query

2 pts

* TASK: add inMailboxes criteria into SearchQuery
** NOTE: implement inMailboxes filtering into 3 backends
** NOTE: must be done before Filter to SearchQuery conversion

2 pts

* TASK: multi-mailbox support in GetMessagesList
** NOTE: add an api in MessageSearchIndex to query regarless of a mailbox
** NOTE: CAPABILITY

2 pts

* TASK: map the Filter POJO tree to a SearchQuery
** NOTE: no Thread* support
** NOTE: generate a toString for the tree

3 pts

* TASK: make GetMessagesList call the search api implementations

2 pts

* TASK: implement some significant search

3 pts

* TASK: handle large subject when indexing (INBOX-381)


== Misc

* TASK: emit a New Account request (on https://id.apache.org/acreq/ ?) for Raphaël

* TASK: generate a website for JMAP documentation with annotations
** NOTE: we already have the commands to generate some html
** NOTE: add the publish process into jenkins (master)
** NOTE: create a container with the html files and static webserver
** NOTE: handle reverse proxy to james.open-paas.org/doc -> jmap spectification; james.open-paas.org/ci -> jenkins

* TASK: Use only mailbox-api into jmap
** NOTE: use only managers, not mappers
** NOTE: write an attachment manager
** NOTE: MessageResult, Header needs some api love, more methods to extract data, etc
** NOTE: SortToComparatorConvertor should be migrated to MessageResult (2 fields : internalDate and id)
** NOTE: MessageResult to MessageId (just have to extract uid for now but unique storage id needed later)
** NOTE: Rewrite MessageFactory to convert a MessageResult into a jmap.message (using mime4j if needed)
** NOTE: Rework mailbox to work with MailboxPath instead of mailboxId (not sure it's ok)
** NOTE: Extends MailboxMetadata to retrieve total messages, unread messages
** NOTE: extract tika extractors into a new sub-project

* TASK: Add 3 gatling scenarios 
** TODO: ask UX team about usages

* TASK: fix bug INBOX-37 about handling cyrillic content in VacationMailet

* TASK: decode email title when it contains charset tags (INBOX-37, to be split)

* TODO: retry INBOX-289
** NOTE: Cannot reproduce, this issue is already closed with this resolution.

* TASK: allow empty subject when sending mail (INBOX-291)
** NOTE: after rereading the spec, in saving draft: "subject: Optional. Defaults to the empty string ("")." So we have to allow subject to be null in input (setMessages), and in this case return empty string as output (getMessages).

* TODO: retry INBOX-298 and/or read the specification
** NOTE: still valide, here is the specification on those properties:
*** textBody: String|null The plain text body part for the message. If there is only an HTML version of the body, a plain text version will be generated from this.
*** htmlBody: String|null The HTML body part for the message if present. If there is only a plain text version of the body, an HTML version will be generated from this.
** NOTE: two cucumber tests are all ready present:
*** Scenario: Retrieving message should return attachments and html body when some attachments and html message
*** Scenario: Retrieving message should return attachments and text body when some attachments and text message
** NOTE: we can handle only htmlBody->textBody conversion for now: https://groups.google.com/forum/#!topic/jmap-discuss/w9tbelGx_ek

* TODO: see what must be done to implement JAMES-1785 (setMessages : moving a message)
** NOTE: we only have to change SetMessagesUpdateProcessor which actually only updates the flags.
** NOTE: we must use the MailboxManager.moveMessages method.
** NOTE: this task should be done after breaking the mappers dependency.
** NOTE: it's a good time to port SetMessagesMethodTest to cucumber

  Scenario: a user can move a message from a mailbox to another
    Given the user has a message in "A" mailbox
    When the user moves the message "["username@domain.tld|A|1"]" to the "B" mailbox
    Then no error is returned
    And the updated list should contain 1 message with id "["username@domain.tld|A|1"]"

** WARNING: needs unique message Id on move

== Questions

* TODO: check that jmap `text` search maps well on what ES do right now
** NOTE: here is the specification from the text property on FilterCondition:
"text: String|null Looks for the text in the from, to, cc, bcc, subject, textBody or htmlBody properties of the message."
** NOTE: the easiest way (without changing the ES indices) is to handle multiple fields in `IndexableMessage`.
For example, `IndexableMessage` may have a `text` attibute which will be the concatenation of `from`, `to`, `cc`, `bcc`, `subject`, `textBody` and `htmlBody`
** NOTE: we may also add a `body` attribute for `textBody` and `htmlBody`
** NOTE: for information: http://stackoverflow.com/questions/22617674/does-elasticsearch-have-compound-indexes#22657490

* TODO: work on tasks ordering to to deliver support for `text` as fast as possible


* How hard would it be to filter on mailbox and/or users when use Filter on GetMessagesList
** Answer: very. Off course no user indexing at all. James filtering API needs a Mailbox to search on. So it is not possible to compose any filter containing requests such as (inMailboxes=... or notInMailboxes=...). If we don't need compositing or a very simple compositing (2 clauses) the problem can be solved in JMAP backend. To have a plain support we need to end or work on unifying UID, ie a message should have a single id whatever is its mailbox. The good news: elasticsearch is already basing its indexing on such an UID, so maybe extending the API could fit our need for now.
* How hard is it the handle mailbox rename for search ?
** Answer : It should work right now because mailboxId doesn't change on rename. We have to write a test anyway.

* Do we have an implementation that works without requiring filesystem and that is fast to start for InMemory tests ?
** Lucene search is not really tested but should support InMemory
** There's a scanning search implementation, it's slow but should work
** IMAP only ask for substring matching, but JMAP suggest full text search
** ES does not conform to IMAP search but is ok for JMAP
** JMAP says `The exact semantics for matching String fields is deliberately not defined to allow for flexibility in indexing implementation, subject to the following` so any impl should be ok, we only have to be careful about test involving tests
** ES helps implementing https://tools.ietf.org/html/rfc6237 
** We can make UidSearchOnIndex and ElasticSearchIntegrationTest to run on all search impl
